import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "./providers";
import Message from "@/components/Message";
import Drawer from "@/components/home/Drawer";
import FloatButton from "@/components/home/FloatButton";
import SettingModal from "@/components/SettingModal";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Telegram Spider',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    console.log("55555")
  return (
    <html lang="zh">
      <head>
          <meta content="yes" name="apple-mobile-web-app-capable"/>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
      </head>
      <body className={inter.className}>
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
            <Message/>
            {children}
            <FloatButton/>
            <Drawer/>
            <SettingModal/>
        </Providers>
      </body>
    </html>
  )
}
