import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "./providers";
import AntdRegistry from "@/lib/AntdRegistry";
import Message from "@/components/Message";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Telegram Spider',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh">
      <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
      </head>
      <body className={inter.className}>
        <Providers>
          <AntdRegistry>
              <Message/>
              {children}
          </AntdRegistry>
        </Providers>

      </body>
    </html>
  )
}
